# Generated by Django 4.2 on 2024-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('eid', models.CharField(max_length=10)),
                ('phone', models.CharField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
